<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>852024e6-b5ff-4f4d-bc11-3fb4b8783ece</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UNIVERSITY.EDUCATION.PLATFORMS.Application\UNIVERSITY.EDUCATION.PLATFORMS.Application.csproj" />
    <ProjectReference Include="..\UNIVERSITY.EDUCATION.PLATFORMS.Domain\UNIVERSITY.EDUCATION.PLATFORMS.Domain.csproj" />
	  <ProjectReference Include="..\UNIVERSITY.EDUCATION.PLATFORMS.ServiceDefaults\UNIVERSITY.EDUCATION.PLATFORMS.ServiceDefaults.csproj" />
	  <ProjectReference Include="..\UNIVERSITY.EDUCATION.PLATFORMS.SERVICE\UNIVERSITY.EDUCATION.PLATFORMS.SERVICE.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="..\.dockerignore" Link=".dockerignore" />
  </ItemGroup>

</Project>
