<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UNIVERSITY.EDUCATION.PLATFORMS.Application\UNIVERSITY.EDUCATION.PLATFORMS.Application.csproj" />
    <ProjectReference Include="..\UNIVERSITY.EDUCATION.PLATFORMS.Domain\UNIVERSITY.EDUCATION.PLATFORMS.Domain.csproj" />
  </ItemGroup>

</Project>
